#!/bin/sh
set -e

# Build Android image assets from assets/icon.svg and assets/background.svg.
# Outputs are gitignored; the app's preBuild also runs this via Gradle.
# Requires: ImageMagick

# shellcheck source=scripts/lib/images.sh
. "$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)/lib/images.sh"
images_require_tools

RES_DIR="$IMAGES_REPO_ROOT/android/app/src/main/res"

echo "Generating Android images from assets/"

# density:scale-in-quarters (mdpi = 4/4, hdpi = 6/4, ...), keeping the math integral.
for entry in mdpi:4 hdpi:6 xhdpi:8 xxhdpi:12 xxxhdpi:16; do
  density=${entry%%:*}
  quarters=${entry#*:}

  # Adaptive icon layers: a 108dp canvas whose inner 72dp is visible, which the
  # mark fills. The themed (monochrome) layer is only its lit segments.
  layer=$((108 * quarters / 4))
  mark=$((72 * quarters / 4))
  render_background "$layer" "$layer" "$RES_DIR/mipmap-$density/ic_launcher_background.png"
  render_foreground "$layer" "$mark" "$RES_DIR/mipmap-$density/ic_launcher_foreground.png"
  render_foreground "$layer" "$mark" "$RES_DIR/mipmap-$density/ic_launcher_monochrome.png" white

  # Status bar icon: white on transparent, 24dp with a 2dp margin.
  notification=$((24 * quarters / 4))
  render_mark "$notification" $((20 * quarters / 4)) \
    "$RES_DIR/drawable-$density/ic_notification.png" white

  # Logo beside the app's title: 40dp (see ui/NoiseScreen.kt).
  logo=$((40 * quarters / 4))
  render_logo "$logo" "$RES_DIR/drawable-$density/ic_logo.png"

  echo "  $density: launcher layers (${layer}px), notification icon (${notification}px), logo (${logo}px)"
done

# Android 12+ splash screens take a solid color, not an image.
mkdir -p "$RES_DIR/values"
cat >"$RES_DIR/values/generated_colors.xml" <<XML
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/buildAndroidImages.sh from assets/background.svg. Do not edit. -->
<resources>
    <color name="splash_background">$(background_average_color)</color>
</resources>
XML
echo "  values/generated_colors.xml"
